version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - sudo yum update -y
      - sudo yum install -y firefox
      - wget https://github.com/mozilla/geckodriver/releases/latest/download/geckodriver-linux64.tar.gz
      - tar -xvzf geckodriver-linux64.tar.gz
      - sudo mv geckodriver /usr/local/bin/
      - geckodriver --version
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running Selenium tests..."
      - python test_script.py
