version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - python3 -m venv selenium_env
      - source selenium_env/bin/activate
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running Selenium tests..."
      - python test_script.py
