version: 0.2

phases:
  install:
    commands:
      - wget "https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US" -O firefox.tar.bz2
      - tar -xjf firefox.tar.bz2
      - sudo mv firefox /opt/
      - sudo ln -s /opt/firefox/firefox /usr/bin/firefox
      - firefox --version
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running Selenium tests..."
      - python test_script.py
